### ISSUE TITLE
How to change default time of tkTimePicker analog clock

### ISSUE THREAD

**Issue by SoftwareByMeir** [PaulleDemon/tkTimePicker#4]
Hi,
Thank you for making this very useful project.  The default time (the time that it shows initially) is 12:59 AM. I want to be able to change the default time to something else.  Is that possible?
[https://stackoverflow.com/questions/72007595/how-to-change-default-time-of-tktimepicker-analog-clock](https://stackoverflow.com/questions/72007595/how-to-change-default-time-of-tktimepicker-analog-clock)

**Comment by PaulleDemon** [comment]
Hi, there @SoftwareByMeir  I just updated the library to fill in your request now you can use the `setHours(10)` to set hours and `setMinutes(50)` to point to different numbers. (Note: you will have to uninstall the library and install the latest version for this)

Example:
```py
from tkinter import *
from tktimepicker import AnalogPicker, AnalogThemes, constants



def pick_time():

    toplevel = Toplevel(root)
    
    picker = AnalogPicker(toplevel)
    picker.setHours(10)
    picker.setMinutes(45)

    picker.pack(fill="both", expand=True)
    theme = AnalogThemes(picker)
    theme.setNavyBlue()


root = Tk()

btn = Button(text="pick time", command=pick_time)
btn.pack()

root.mainloop()
```

**Comment by PaulleDemon** [comment]
@SoftwareByMeir If you face any other issues let me know in 48hrs otherwise just comment under this so I can close the issue :)

**Comment by SoftwareByMeir** [comment]
Thank you, the setHours and setMinutes work great.  Is it possible to also set the period (AM/PM)?

**Comment by PaulleDemon** [comment]
@SoftwareByMeir yes `AnalogPicker` picker takes `period` as a parameter which is set to AM by default you can change this to PM using `AnalogPicker(parent, period=constants.PM)`

**Comment by SoftwareByMeir** [comment]
Perfect, thank you very much.  I will post this as an answer on the [stackoverflow question](https://stackoverflow.com/questions/72007595/how-to-change-default-time-of-tktimepicker-analog-clock) that I asked, unless you want to post the answer so that you get the rep.

**Comment by PaulleDemon** [comment]
@SoftwareByMeir Sure you can go ahead and post an answer. Thank you have a great day.

**Comment by Destaq** [comment]
> @SoftwareByMeir If you face any other issues let me know in 48hrs otherwise just comment under this so I can close the issue :)

Hi @PaulleDemon , not the original poster but just wanted to chip in with my own default-time-related question. Is it possible to set a default time for the `SpinTimePickerOld` class? Read through the docs and been trying to configure things myself for the past half-hour or so, but no luck.

**Comment by PaulleDemon** [comment]
@Destaq I agree the documentation is confusing and contains all the unnecessary details; I'll try to update it whenever I get time.

Now coming to your question. Currently, there isn't a direct way to set the default value. However, there is a workaround.

```py
var = tk.IntVar(top)
var.set(8)
time_picker._12HrsTime.config(textvariable=var) # for 12 hrs timepicker
time_picker._24HrsTime.config(textvariable=var) # for 24 hrs timepicker
time_picker._minutes.config(textvariable=var) # for minutes
```
You will have to give different control variables (`var=tk.IntVar()`) for each of these to be able to control them independently.

**Comment by Destaq** [comment]
> @Destaq I agree the documentation is confusing and contains all the unnecessary details; I'll try to update it whenever I get time.
> 
> Now coming to your question. Currently, there isn't a direct way to set the default value. However, there is a workaround.
> 
> ```python
> var = tk.IntVar(top)
> var.set(8)
> time_picker._12HrsTime.config(textvariable=var) # for 12 hrs timepicker
> time_picker._24HrsTime.config(textvariable=var) # for 24 hrs timepicker
> time_picker._minutes.config(textvariable=var) # for minutes
> ```
> 
> You will have to give different control variables (`var=tk.IntVar()`) for each of these to be able to control them independently.

Well, it sure isn't pretty, but works like a charm. Thank you for the quick response!
