### ISSUE TITLE
How to change default time of TKTimePiker SpinTimePickerOld

### ISSUE THREAD

**Issue by MarioLung** [PaulleDemon/tkTimePicker#9]
Hey,

addHours or addMinutes dosent work

AttributeError: 'SpinTimePickerOld' object has no attribute 'setMinutes'

any Infomations or Hints

thx
Mario

**Comment by PaulleDemon** [comment]
Hi, @MarioLung there isn't a direct way to do this but there is a workaround. You'll have to set a text variable to spin-picker as shown

```py
time_picker = SpinTimePickerOld(top)
var = tk.IntVar(value=15)

time_picker._12HrsTime.config(textvariable=var)
time_picker.addHours12()
 time_picker.addMinutes()
```

You'll have to do the same thing with minutes `time_picker._minutes.config(textvariable=var)`.

If you have any further questions, drop a message
